- hosts: localhost
  vars:
    source_key: "./keys/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - include_tasks: tasks/update-repo.yml
      tags: all
  tasks:
    - include_tasks: tasks/font.yml
      tags: 
        - font 
        - fonts
    - include_tasks: tasks/git-setup.yml
      tags: git
    - include_tasks: tasks/ssh.yml
      tags: ssh
    - include_tasks: tasks/npm.yml
      tags: npm
    - include_tasks: tasks/zsh.yml
      tags: zsh
    - include_tasks: tasks/nvim.yml
      tags: nvim
    - include_tasks: tasks/yabai.yml
      tags: yabai
    - include_tasks: tasks/skhd.yml
      tags: skhd
    - include_tasks: tasks/obsidian.yml
      tags: obsidian
    - include_tasks: tasks/karabiner-elements.yml
      tags: karabiner
    - include_tasks: tasks/cli.yml
      tags: cli
    - include_tasks: tasks/terminal.yml
      tags: terminal
    - include_tasks: tasks/browser.yml
      tags: browser
    - include_tasks: tasks/tailscale.yml
      tags: tailscale
