- hosts: localhost
  vars:
    source_key: "./keys/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - include_tasks: tasks/update-repo.yml
      tags: all
  tasks:
    - include_tasks: tasks/git-setup.yml
      tags: all
    - include_tasks: tasks/ssh.yml
      tags: ssh
    - include_tasks: tasks/npm.yml
      tags: 
        - nvm
        - npm
    - include_tasks: tasks/zsh.yml
      tags: zsh
    - include_tasks: tasks/nvim.yml
      tags: nvim
      
