- hosts: localhost
  vars:
    source_key: "./keys/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  pre_tasks:
    - include_tasks: tasks/update-repo.yml
      tags: all
  tasks:
    - include_tasks: tasks/font.yml
      tags: 
        - font 
        - fonts
    - include_tasks: tasks/git-setup.yml
      tags: all
    - include_tasks: tasks/ssh.yml
      tags: ssh
    - include_tasks: tasks/npm.yml
      tags: npm
    - include_tasks: tasks/zsh.yml
      tags: zsh
    - include_tasks: tasks/nvim.yml
      tags: nvim
    - include_tasks: tasks/yabai.yml
      tags: yabai
    - include_tasks: tasks/skhd.yml
      tags: skhd
    - include_tasks: tasks/mac-shortcut.yml
      tags: macos-shortcut
    - include_tasks: tasks/i3.yml
      tags: i3
    - include_tasks: tasks/obsidian.yml
      tags: obsidian
    - include_tasks: tasks/karabiner-elements.yml
      tags: karabiner
