- name: Add floorp gpg key and repository
  when: ansible_os_family == "Debian"
  tags:
    - floorp 
    - browser
  become: true
  block:
    - name: floorp | apt key
      ansible.builtin.get_url:
        url: https://ppa.ablaze.one/KEY.gpg
        dest: /usr/share/keyrings/Floorp.gpg

    - name: floorp | apt repo
      ansible.builtin.get_url:
        url: https://ppa.ablaze.one/Floorp.list
        dest: /etc/apt/sources.list.d/Floorp.list
        mode: '0644'
        force: yes
        
    - name: thorium | apt repo
      ansible.builtin.get_url:
        url: http://dl.thorium.rocks/debian/dists/stable/thorium.list
        dest: /etc/apt/sources.list.d/thorium.list
        mode: '0644'
        force: yes

    - name: Update apt
      apt:
        force_apt_get: true
        update_cache: true
        state: present
    - name: Install thorium and floorp on debian
      ansible.builtin.apt:
        name:
          - floorp
          - thorium-browser
        state: latest

- name: Install firefox on macOS
  when: ansible_os_family == "Darwin"
  homebrew:
    name: firefox
    state: latest
    update_homebrew: true
  tags: 
    - browser
    - firefox
