- name: Add floorp gpg key and repository
  when: ansible_os_family == "Debian"
  tags:
    - browser
  become: true
  block:
    - name: setup brave gpg key
      ansible.builtin.shell: |
        curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"| tee /etc/apt/sources.list.d/brave-browser-release.list
      become: true

    - name: Update apt
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      become: true
        
    - name: Install brave and firefox on debian
      ansible.builtin.apt:
        name:
          - brave-browser
          - firefox
        state: latest

- name: Install firefox on macOS
  when: ansible_os_family == "Darwin"
  homebrew:
    name: firefox
    state: latest
    update_homebrew: true
  tags: 
    - browser
    - firefox
