- name: Check if 'cinnamon' is a valid command
  when: ansible_os_family == "Debian"
  tags: 
    - cinnamon
  command: which cinnamon
  register: cinnamon_check
  ignore_errors: yes
- name: Install wmctrl shortcuts 
  when: ansible_os_family == "Debian" and cinnamon_check.rc == 0
  tags: 
    - cinnamon
  vars:
    apps:
      - wezterm
      - nemo
      - floorp
    shortcuts_dir: "{{ lookup('env', 'HOME') }}/shortcuts"
  block:
    - name: Install wmctrl on debian
      ansible.builtin.apt:
        name:
          - wmctrl
        state: latest
    - name: Create shortcut directory
      file:
        path: "{{ shortcuts_dir }}"
        state: directory
        mode: '0755'
    - name: Create shortcut directory
      loop: "{{ apps }}"
      loop_control:
        loop_var: app 
      copy:
        src: "../dotfiles/cinnamon/{{app}}.sh"
        dest: "{{ lookup('env', 'HOME') }}/shortcuts/"
        mode: 0744
