- name: Update apt
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - cli
- name: Install cli related packages
  become: true
  ansible.builtin.apt:
    name:
      - htop # process status 
      - bat # cat alternative 
      - fzf # terminal auto complete 
      - ripgrep # search 
  when: ansible_os_family == "Debian"
  tags:
    - cli
