- name: Install nerd font
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory
  tags: 
    - font
    - fonts 

- name: Check if font exists
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/SauceCodeProNerdFont-Regular.ttf"
  register: font_exists
  ignore_errors: yes
  tags: 
    - font 
    - fonts 

- name: Copy font
  when: font_exists is failed
  copy:
    src: "../fonts/"
    dest: "{{ lookup('env', 'HOME') }}/.fonts"
    mode: 0700
  tags: 
    - font 
    - fonts 

