- name: Install nerd font
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory
  when: ansible_os_family == "Debian"
  tags: 
    - font
    - fonts 
- name: Check if font exists (debian)
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/SauceCodeProNerdFont-Regular.ttf"
  register: font_exists
  ignore_errors: yes
  tags: 
    - font 
    - fonts 
  when: ansible_os_family == "Debian"
- name: Copy font (debian)
  when: font_exists is failed
  copy:
    src: "../fonts/"
    dest: "{{ lookup('env', 'HOME') }}/.fonts"
    mode: 0700
  tags: 
    - font 
    - fonts 
  when: ansible_os_family == "Debian"

- name: Install nerd font MacOS
  when: ansible_os_family == "Darwin"
  community.general.homebrew_cask:
    name: 
      - 'font-meslo-lg-nerd-font'
      - 'font-sauce-code-pro-nerd-font'
      - 'font-fira-code-nerd-font'
    state: latest
    update_homebrew: true
  tags: 
    - font
    - fonts
