- name: Update apt
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - i3
- name: add required repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
  loop:
    - 'ppa:aslatter/ppa' # for alacritty
  when: ansible_os_family == "Debian"
  tags:
    - i3
- name: install i3 and related packages
  become: true
  ansible.builtin.apt:
    name:
      - i3 # i3  window manager 
      - polybar # for status bar 
      - rofi # dmenu alternative 
      - alacritty # terminal
      - htop # process status 
      - bat # cat alternative 
      - fzf # terminal auto complete 
      - ripgrep # search 
      - arandr # video output setting 
      - xclip # clip board 
      - clipit # clip tray icon 
      - xcape # remap caplock to escape
      - flameshot # screen shot 
  when: ansible_os_family == "Debian"
  tags:
    - i3
- name: Copy i3 config into the config folder
  copy: 
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/"

  loop: 
    - "../dotfiles/i3"
    - "../dotfiles/polybar"
    - "../dotfiles/rofi"
    - "../dotfiles/alacritty"
  when: ansible_os_family == "Debian"
  tags:
    - i3
- name: Copy i3 keymap into the root folder
  copy: 
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/"
    mode: "u=rwx,g=rx,o=rx"
  loop: 
    - "../dotfiles/keymap.sh"
  when: ansible_os_family == "Debian"
  tags:
    - i3
- name: Ensure poly bar, rofi launcher and keymap script are executable
  file: 
    dest: "{{ item }}"
    "mode": "u=rwx,g=rx,o=rx"

  loop:
    - "{{ lookup('env', 'HOME') }}/.config/rofi/launchers/type-2/launcher.sh"
    - "~/.config/rofi/powermenu/type-4/powermenu.sh"
    - "~/.config/polybar/launch.sh"
    - "~/.config/polybar/grayblocks/launch.sh"
    - "~/.config/polybar/grayblocks/preview.sh"
    - "~/keymap.sh"
  tags:
    - i3
- name: Ensure poly bar, rofi launcher and keymap script are executable
  file: 
    dest: "{{ item }}"
    "recurse": true
    "mode": "u=rwx,g=rx,o=rx"
  loop:
    - "~/.config/polybar/grayblocks/scripts"
  tags:
    - i3
