- name: Ensuring Homebrew is installed MacOS
  when: ansible_os_family == "Darwin"
  stat:
    path: /usr/local/bin/brew
  register: nvim_homebrew_exist
  tags: karabiner

- name: Install karabiner-elements MacOS 
  when: ansible_os_family == "Darwin"
  homebrew:
    name: karabiner-elements
    state: latest
    update_homebrew: true
  tags: karabiner

