- name: Ensuring Homebrew is installed MacOS
  when: ansible_os_family == "Darwin"
  stat:
    path: /usr/local/bin/brew
  register: nvim_homebrew_exist
  tags: karabiner

- name: Install karabiner-elements MacOS 
  when: ansible_os_family == "Darwin"
  homebrew_cask:
    name: karabiner-elements
    state: latest
    update_homebrew: true
  tags: karabiner

- name: Install karabiner-elements Config MacOs 
  when: ansible_os_family == "Darwin"
  file:
    path: "~/.config/karabiner"
    state: directory
    mode: "0755"
  tags: karabiner

- name: Install karabiner-elements main config MacOs 
  when: ansible_os_family == "Darwin"
  copy:
    src: "../dotfiles/karabiner/karabiner.json"
    dest: "~/.config/karabiner/karabiner.json"
    mode: "0644"
  tags: karabiner

- name: Install karabiner complex modifications MacOs
  when: ansible_os_family == "Darwin"
  copy:
    src: "../dotfiles/karabiner/assets/complex_modifications"
    dest: "~/.config/karabiner/assets/"
    mode: "0644"
  tags: karabiner
