- name: Install nvm
  become: no
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "$HOME"
    creates: "$HOME/.nvm/nvm.sh"
  tags: 
    - nvm
    - npm
- name: Install node and set version
  become: no
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install node"
    creates=/home/{{ ansible_user_id }}/.nvm/alias
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/*"
  tags: 
    - nvm 
    - npm
