- name: Install System Packages 1 
  become: true
  when: >
    ansible_os_family == "Debian" 
    or ansible_os_family == "RedHat"
  apt:
    name: ["build-essential", "cmake", "ninja-build", "gettext", "unzip", "curl"]
  tags:
    - nvim

- name: Clone Neovim
  when: >
    ansible_os_family == "Debian" 
    or ansible_os_family == "RedHat"
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - nvim


      
- name: Build neovim
  when: >
    ansible_os_family == "Debian" 
    or ansible_os_family == "RedHat"
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - nvim

- name: Install neovim
  when: >
    ansible_os_family == "Debian" 
    or ansible_os_family == "RedHat"
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - nvim

- name: Ensuring Homebrew is installed MacOS
  stat:
    path: /usr/local/bin/brew
  register: nvim_homebrew_exist
  when: ansible_os_family == "Darwin"
  tags: nvim

- name: Install neo vim MacOS 
  when: ansible_os_family == "Darwin"
  homebrew:
    name: neovim
    state: latest
    update_homebrew: true
  tags: nvim

- name: copy dot files
  copy:
    src: "../dotfiles/nvim"
    dest: "$HOME/.config/"
  tags: nvim
