- name: Print tailscale install warning
  when:
    - ansible_os_family != "Debian"
  tags:
    - tailscale
    - personal
  debug:
    msg: >-
      Warning Unable to install tailscale for OS {{ ansible_os_family }}.
      Please update tasks/tailscale.yml to support it.

- name: Install tailscale
  when: ansible_os_family == "Debian"
  tags:
    - tailscale 
    - personal
  become: true
  ansible.builtin.shell:
    curl -fsSL https://tailscale.com/install.sh | sh
