###########################################
# Debian Setup ----------------------------
###########################################
- name: Update apt
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - terminal

- name: install alacritty and wezterm related packages
  become: true
  ansible.builtin.apt:
    name:
      - wezterm # main terminal
      - alacritty # backup terminal
    state: latest
  when: ansible_os_family == "Debian"
  tags:
    - terminal
- name: Copy wezterm config into the config folder (Debian)
  copy: 
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/"
  when: ansible_os_family == "Debian"
  loop: 
    - "../dotfiles/wezterm/.wezterm.lua"
  tags:
    - terminal

- name: Copy config into the config folder (Debian)
  copy: 
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/"
  when: ansible_os_family == "Debian"
  loop: 
    - "../dotfiles/alacritty"
  tags:
    - terminal

###########################################
# MAC-OS Setup ----------------------------
###########################################
 
- name: Install wezterm MacOS 
  when: ansible_os_family == "Darwin"
  community.general.homebrew_cask:
    name: wezterm
    state: latest
    update_homebrew: true
  tags: terminal

- name: Install alacritty (backup) MacOS 
  when: ansible_os_family == "Darwin"
  homebrew:
    name: alacritty
    state: latest
    update_homebrew: true
  tags: terminal
- name: Install alacritty themes
  when: ansible_os_family == "Darwin"
  ansible.builtin.git:
    repo: 'https://github.com/alacritty/alacritty-theme'
    dest: "~/.config/alacritty/themes"
  tags: terminal
- name: Copy config into the config folder
  copy: 
    src: "{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/.config/"
  loop: 
    - "../dotfiles/alacritty"
  tags:
    - terminal
  when: ansible_os_family == "Darwin"

# - name: Install iterm2 MacOS 
#   when: ansible_os_family == "Darwin"
#   homebrew:
#     name: iterm2
#     state: latest
#     update_homebrew: true
#   tags: terminal

