- name: Install tmux MacOS 
  when: ansible_os_family == "Darwin"
  tags: tmux
  homebrew:
    name: 
      - tmux
    state: latest
    update_homebrew: true

- name: Install tmux (debian)
  when: ansible_os_family == "Debian"
  tags: tmux
  apt: 
    name: 
      - tmux
    state: latest 
  become: true

- name: copy tmux config to home MacOS
  when: ansible_os_family == "Darwin" or ansible_os_family == "Debian"
  tags: tmux
  copy:
    src: "{{ item.src }}"
    dest: "~/"
    mode: "0644"
  loop: 
    - src: "../dotfiles/tmux/.tmux.conf"

- name: Install tpm
  when: ansible_os_family == "Darwin" or ansible_os_family == "Debian"
  tags: tmux
  ansible.builtin.git:
    repo: 'https://github.com/tmux-plugins/tpm'
    dest: '~/.tmux/plugins/tpm'

