- name: Update apt
  become: true
  apt:
    force_apt_get: true
    update_cache: true
    state: present
  when: ansible_os_family == "Debian"
- name: Update dnf
  become: true
  dnf:
    security: true
    state: latest
  when: ansible_os_family == "RedHat"
