- name: Install wmctrl shortcuts 
  when: ansible_os_family == "Debian"
  tags: 
    - wmctrl
  vars:
    apps:
      - wezterm
      - brave
    shortcuts_dir: "{{ lookup('env', 'HOME') }}/shortcuts"
  block:
    - name: Install wmctrl on debian
      ansible.builtin.apt:
        name:
          - wmctrl
        state: latest
    - name: Create shortcut directory
      file:
        path: "{{ shortcuts_dir }}"
        state: directory
        mode: '0755'
    - name: Create shortcut directory
      loop: "{{ apps }}"
      loop_control:
        loop_var: app 
      copy:
        src: "../dotfiles/wmctrl/{{app}}.sh"
        dest: "{{ lookup('env', 'HOME') }}/shortcuts/"
        mode: 0744
