# Debian Specific Setup
- name: debian specific zsh setup steps
  tags: zsh
  when: ansible_os_family == "Debian"
  block:
    - name: Install zsh utility debian
      apt: 
        name: 
          - zsh
          - curl
          - eza # better ls
          - zoxide # better cd 
          - bat # better cat
          - htop # process status 
          - fzf # terminal auto complete 
          - ripgrep # search 
          - tldr
        state: latest 
      become: true
      when: ansible_os_family == "Debian"

    - name: copy custom zsh for Debian 
      when: ansible_os_family == "Debian"
      tags: zsh
      copy:
        src: "../dotfiles/debian/.zshrc.local"
        dest: "~/"
        mode: "0644"
        force: false

# MacOS Specific Setup
- name: macOS specific zsh setup steps
  tags: zsh
  when: ansible_os_family == "Darwin"
  block:
    - name: Install zsh utility MacOS 
      homebrew:
        name: # no need to install zsh and curl as it is built in to macOS
          - eza # better ls
          - zoxide # better cd 
          - bat # better cat
          - htop # process status 
          - fzf # terminal auto complete 
          - ripgrep # search 
          - tldr # better manual
        state: latest
        update_homebrew: true
    - name: copy custom zsh for MacOS
      copy:
        src: "../dotfiles/macOS/.zshrc.local"
        dest: "~/"
        mode: "0644"
        force: false

# Global Configuration Starts Here
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: true
  tags: zsh

- name: Inform user that chsh require logout and log back in to take effect
  debug: msg="Updated zsh as default shell. chsh require logout and log back in to take effect"
  tags: zsh
  
- name: Check that the somefile.conf exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  tags: zsh

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: oh_my_stats.stat.exists == False
  tags: zsh
  
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: zsh

- name: Install zsh-syntax-highlighting
  tags: zsh
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"

- name: Install zsh-autocomplete
  tags: zsh
  ansible.builtin.git:
    repo: 'https://github.com/marlonrichert/zsh-autocomplete.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autocomplete"
    depth: 1

- name: Install zsh-completion
  tags: zsh
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-completions"
    depth: 1

- name: Install Power Level 10k
  tags: zsh
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"

- name: Copy .zshrc, .alias, and .p10k.zsh
  copy:
    src: "{{ item.src }}"
    dest: "~/"
    mode: "0644"
  loop: 
    - src: "../dotfiles/.zshrc"
    - src: "../dotfiles/.p10k.zsh"
    - src: "../dotfiles/.aliases"
  tags: zsh
