- name: Install ZSH
  apt: 
    name: 
      - zsh
      - curl 
    state: present
  become: true
  when: ansible_os_family == "Debian"
  tags: zsh
# TODO add MacOS and Red Hat version here

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  become: true
  tags: zsh

- name: Check that the somefile.conf exists
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_stats
  tags: zsh

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  when: oh_my_stats.stat.exists == False
  tags: zsh
  
- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: zsh

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags: zsh

- name: Install zsh-autocomplete
  ansible.builtin.git:
    repo: 'https://github.com/marlonrichert/zsh-autocomplete.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autocomplete"
    depth: 1
  tags: zsh

- name: Install zsh-completion
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-completion"
    depth: 1
  tags: zsh

- name: Install Power Level 10k
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "~/.oh-my-zsh/custom/themes/powerlevel10k"
  tags: zsh

- name: Copy .zshrc, .alias, and .p10k.zsh
  copy:
    src: "{{ item.src }}"
    dest: "~/"
    mode: "0644"
  loop: 
    - src: "../dotfiles/.zshrc"
    - src: "../dotfiles/.p10k.zsh"
    - src: "../dotfiles/.aliases"
  tags: zsh
- name: copy custom zsh for MacOS
  when: ansible_os_family == "Darwin"
  copy:
    src: "../dotfiles/macOS/.zshrc.local"
    dest: "~/"
    mode: "0644"
  tags: zsh
